### ISSUE TITLE
Logging wtf? to console

### ISSUE THREAD

**Issue by razor-x** [bmatcuk/brunch-static#3]
[This line](https://github.com/bmatcuk/brunch-static/blob/c6362733082bd0c96a7c847d26d82d7706c33965/index.js#L59) is giving me this on every brunch run:

```
11 Sep 21:31:48 - info: application started on http://127.0.0.1:3333/ (lo)
wtf?
wtf?
```

**Comment by bmatcuk** [comment]
lol, sorry about that! Debugging output that I forgot to remove =) I've cut a v1.2.1 that removes the line.
