### ISSUE TITLE
Add Nunjucks processor

### ISSUE THREAD

**Issue by olimination** [bmatcuk/brunch-static#5]
Hi!

we plan to use in our project the "Nunjucks" templating language: https://mozilla.github.io/nunjucks/
I have found this old Brunch plugin here: https://github.com/brunch/nunjucks-brunch
But I wonder if it would make sense and if it would be technically possible to use this project to add a new Nunjucks processor.
What do you think?

**Comment by bmatcuk** [comment]
I'm really sorry it took me forever to get to this! I'm sure by now, you've moved on to something else, but I did create a nunjucks processor, should you ever come back to this: https://github.com/bmatcuk/njk-brunch-static

**Comment by olimination** [comment]
Hi @bmatcuk thanks for this! I could not yet test it for my corresponding project, because I needed to pause it for the moment. But for sure I will check it as soon as I will continue. Thanks again!

**Comment by bmatcuk** [comment]
You're welcome! Let me know if you run into any trouble! =)
